version: "3.8"

services:
  api-calculator:
    build:
      context: ./BE
    ports:
      - "5001:5001"
    environment:
      - REMOTE_SERVER_ADDRESS=http://api-calculator:5001

  frontend:
    build:
      context: ./FE
    ports:
      - "8080:80"
    environment:
      - API_URL=http://api-calculator:5001
